# spring.profiles.activeにデフォルトでアクティブなプロファイルを指定
spring:
  profiles:
    active: dev

# "---"でプロファイルを区切る
# プロファイル名はspring.profilesに書く
---
spring:
  profiles: dev
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/skill?autoReconnect=true&useSSL=false
    username: wicresoft
    password: wsjp
    driverClassName: com.mysql.jdbc.Driver

---
spring:
  profiles: production
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/skill?autoReconnect=true&useSSL=false
    username: wicresoft
    password: wsjp
    driverClassName: com.mysql.jdbc.Driver